// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANS6VJzc1FpScK7_MzPZknRvvz8cxz1fE',
    appId: '1:212299365387:web:3c77749be6378f0485db0e',
    messagingSenderId: '212299365387',
    projectId: 'paishop-46226',
    authDomain: 'paishop-46226.firebaseapp.com',
    storageBucket: 'paishop-46226.firebasestorage.app',
    measurementId: 'G-RKK7ZQM58C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvzcLOC7hTmYBYjnNDJxIpFT0XJ_Rp6zc',
    appId: '1:212299365387:android:baf1c6092588b75485db0e',
    messagingSenderId: '212299365387',
    projectId: 'paishop-46226',
    storageBucket: 'paishop-46226.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRgtSlAmMqNtc3Y-fGWk0cAMWXncuJg0Y',
    appId: '1:212299365387:ios:104c74c35788f28d85db0e',
    messagingSenderId: '212299365387',
    projectId: 'paishop-46226',
    storageBucket: 'paishop-46226.firebasestorage.app',
    iosBundleId: 'com.example.aiShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRgtSlAmMqNtc3Y-fGWk0cAMWXncuJg0Y',
    appId: '1:212299365387:ios:104c74c35788f28d85db0e',
    messagingSenderId: '212299365387',
    projectId: 'paishop-46226',
    storageBucket: 'paishop-46226.firebasestorage.app',
    iosBundleId: 'com.example.aiShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANS6VJzc1FpScK7_MzPZknRvvz8cxz1fE',
    appId: '1:212299365387:web:8d8cc3eb64e68f3085db0e',
    messagingSenderId: '212299365387',
    projectId: 'paishop-46226',
    authDomain: 'paishop-46226.firebaseapp.com',
    storageBucket: 'paishop-46226.firebasestorage.app',
    measurementId: 'G-DETPH3S9YK',
  );
}
